### ISSUE TITLE
Do we have lemmas relating • to ⇑ ?

### ISSUE THREAD

**Issue by JoeyEremondi** [jsiek/abstract-binding-trees#1]
Sorry, not so much of an issue as asking for help. I'm wondering if anywhere in the library there's the lemma that `⟪ t  • ρ ⟫(⇑ M) ≡ ⇑ (⟪ ρ ⟫ M)`.

The idea is that 0 can't occur in `(⇑ M)` since all of its variables are incremented.
I've looked through the library and haven't found a proof of this, though it looks like `sub-tail` is similar. Am I missing a lemma somewhere, or is this just something I'd need to prove by hand?

**Comment by jsiek** [comment]
Hi Joey,

Take a look at FV-rename, rename-FV-⊥, FV-↑1-0, and perhaps FV-rename-fwd at the
bottom of Renaming.agda. They don't do the exact lemma that you want, but they
are in the ball-park.

Cheers,
Jeremy

**Comment by JoeyEremondi** [comment]
Thanks for the quick response! I was able to prove what I needed in my case using `sub-sub` and `rename-subst`, but those functions are great to know about.
Also, thanks for making this library! Overall it's been a pleasure to use.

**Comment by jsiek** [comment]
You're very welcome! And if you create new lemmas that you think might be useful for other people, I encourage you to make a pull request.

Cheers,
Jeremy
