### ISSUE TITLE
what is the algorithm for parsing strings to abts?

### ISSUE THREAD

**Issue by brando90** [jsiek/abstract-binding-trees#4]
Hi, sorry this is not much of an issue but a question. I was wondering, is there a description somewhere of how to get a parser for ABTs given strings? 

Thanks for sharing your code and for your time!

**Comment by jsiek** [comment]
I'd recommend first parsing into a normal abstract syntax tree that uses strings for names.
Then you can convert to an abstract binding tree via the usual translation into de Bruijn indices,
which to summarize, is that you recursively traverse the program passing along as a parameter the list of in-scope variables. When you get to the occurrence of a variable, find it's position in this list, and use that as the de Bruijn index.
