### ISSUE TITLE
Missing ▷→▷ updates in BlogTypeSafety10Easy4Med1Hard.lagda.md

### ISSUE THREAD

**Issue by shhyou** [jsiek/abstract-binding-trees#8]
A recent update 0aedac1a4c8b folds the introduction `→ᵒI` into the rule `▷→▷`, but the blog post has not been updated:

https://github.com/jsiek/abstract-binding-trees/blob/66e0eae4e91eddc51086bfcd9abb24c4cc964616/src/rewriting/examples/BlogTypeSafety10Easy4Med1Hard.lagda.md?plain=1#L1243-L1247

**Comment by jsiek** [comment]
Thanks! I've updated the blog post.
